import re

with open("internal/db/seed.go", "r") as f:
    content = f.read()

new_assemblies = """var seedAssemblyItems = []seedAssembly{
	{
		name:         Face Frame Box,
		assemblyType: models.AssemblyTypeBox,
		style:        models.StyleFaceFrame,
		core:         1/2" Prefinished Birch Plywood,
		back:         1/4" Prefinished Birch Plywood,
		faceLumber:   4/4 Select Poplar (Paint-Grade),
		panelType:    models.PanelTypeFlat,
		frameJoinery: models.FrameJoineryCopeAndStick,
		buildLabor:   0.0,
		isDefault:    true,
	},
	{
		name:         Frameless Melamine Box,
		assemblyType: models.AssemblyTypeBox,
		style:        models.StyleFrameless,
		core:         5/8" White Melamine,
		back:         1/4" White Hardboard / Melamine Back,
		edgeband:     White PVC Edgeband (15/16"),
		panelType:    models.PanelTypeFlat,
		frameJoinery: models.FrameJoineryCopeAndStick,
		buildLabor:   0.0,
		isDefault:    false,
	},
	{
		name:         5-Piece Shaker Door,
		assemblyType: models.AssemblyTypeDoor,
		style:        models.StyleFaceFrame,
		core:         4/4 Select Poplar (Door Stock),
		panel:        1/4" MDF (Door Panel),
		hardware:     Blum Soft-Close 110 Hinge + Plate,
		panelType:    models.PanelTypeFlat,
		frameJoinery: models.FrameJoineryCopeAndStick,
		isOutsourced: false,
		buildLabor:   0.9,
		isDefault:    true,
	},
	{
		name:           Solid Raised Panel Door,
		assemblyType:   models.AssemblyTypeDoor,
		style:          models.StyleFaceFrame,
		core:           4/4 Superior Alder,
		panel:          4/4 Superior Alder,
		hardware:       Blum Soft-Close 110 Hinge + Plate,
		panelType:      models.PanelTypeRaisedSolid,
		frameJoinery:   models.FrameJoineryCopeAndStick,
		isOutsourced:   false,
		panelPrepLabor: 0.4,
		buildLabor:     1.1,
		isDefault:      false,
	},
	{
		name:         MDF Raised Panel Door,
		assemblyType: models.AssemblyTypeDoor,
		style:        models.StyleFaceFrame,
		core:         4/4 Select Poplar (Door Stock),
		panel:        3/4" MDF (Slab),
		hardware:     Blum Soft-Close 110 Hinge + Plate,
		panelType:    models.PanelTypeRaisedSheet,
		frameJoinery: models.FrameJoineryCopeAndStick,
		isOutsourced: false,
		buildLabor:   1.1,
		isDefault:    false,
	},
	{
		name:         Slab Door,
		assemblyType: models.AssemblyTypeDoor,
		style:        models.StyleFaceFrame,
		core:         3/4" MDF (Slab),
		hardware:     Blum Soft-Close 110 Hinge + Plate,
		panelType:    models.PanelTypeFlat,
		frameJoinery: models.FrameJoinerySlab,
		isOutsourced: false,
		buildLabor:   0.3,
		isDefault:    false,
	},
	{
		name:         Outsourced Raw Door,
		assemblyType: models.AssemblyTypeDoor,
		style:        models.StyleFaceFrame,
		panelType:    models.PanelTypeFlat,
		frameJoinery: models.FrameJoineryCopeAndStick,
		isOutsourced: true,
		prepLabor:    0.08,
		isDefault:    false,
	},
	{
		name:         Matching 5-Piece Shaker Front,
		assemblyType: models.AssemblyTypeDrawerFront,
		style:        models.StyleFaceFrame,
		core:         4/4 Select Poplar (Door Stock),
		panel:        1/4" MDF (Door Panel),
		panelType:    models.PanelTypeFlat,
		frameJoinery: models.FrameJoineryCopeAndStick,
		isOutsourced: false,
		buildLabor:   0.7,
		isDefault:    true,
	},
	{
		name:         Solid Slab Front,
		assemblyType: models.AssemblyTypeDrawerFront,
		style:        models.StyleFaceFrame,
		core:         3/4" MDF (Slab),
		panelType:    models.PanelTypeFlat,
		frameJoinery: models.FrameJoinerySlab,
		isOutsourced: false,
		buildLabor:   0.25,
		isDefault:    false,
	},
	{
		name:         Outsourced Raw Front,
		assemblyType: models.AssemblyTypeDrawerFront,
		style:        models.StyleFaceFrame,
		panelType:    models.PanelTypeFlat,
		frameJoinery: models.FrameJoineryCopeAndStick,
		isOutsourced: true,
		prepLabor:    0.05,
		isDefault:    false,
	},
	{
		name:             5/8" Dovetail Birch (Undermount),
		assemblyType:     models.AssemblyTypeDrawerBox,
		style:            models.StyleFaceFrame,
		core:             1/2" 5x5 9-Ply Russian Birch,
		back:             1/4" Prefinished Birch Plywood,
		hardware:         Blum 21" Undermount Soft-Close Slides (Pair),
		isOutsourced:     false,
		requiresFinish:   true,
		requiresEdgeband: false,
		panelType:        models.PanelTypeFlat,
		frameJoinery:     models.FrameJoineryCopeAndStick,
		finishLabor:      0.1,
		buildLabor:       0.4,
		isDefault:        true,
	},
	{
		name:             Standard Stapled Melamine (Side-Mount),
		assemblyType:     models.AssemblyTypeDrawerBox,
		style:            models.StyleFaceFrame,
		core:             5/8" White Melamine,
		back:             1/4" White Hardboard / Melamine Back,
		hardware:         Side-Mount Ball Bearing Slides 22" (Pair),
		isOutsourced:     false,
		requiresFinish:   false,
		requiresEdgeband: true,
		panelType:        models.PanelTypeFlat,
		frameJoinery:     models.FrameJoineryCopeAndStick,
		finishLabor:      0.0,
		buildLabor:       0.25,
		isDefault:        false,
	},
	{
		name:         Outsourced / Buyout Drawer Box,
		assemblyType: models.AssemblyTypeDrawerBox,
		style:        models.StyleFaceFrame,
		panelType:    models.PanelTypeFlat,
		frameJoinery: models.FrameJoineryCopeAndStick,
		isOutsourced: true,
		prepLabor:    0.08,
		isDefault:    false,
	},
}"""

content = re.sub(r'var seedAssemblyItems = \[\]seedAssembly\{[\s\S]*?\n\}', new_assemblies, content)

with open("internal/db/seed.go", "w") as f:
    f.write(content)
