// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddQuoteBuyout(arg1:models.QuoteBuyout):Promise<void>;

export function AddQuoteCabinet(arg1:models.QuoteCabinet):Promise<void>;

export function CalculateCabinetCost(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number,arg6:boolean):Promise<models.CabinetCostBreakdown>;

export function CalculateCabinetCostOverride(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number,arg6:number,arg7:number,arg8:number,arg9:boolean):Promise<models.CabinetCostBreakdown>;

export function DeleteAssembly(arg1:number):Promise<void>;

export function DeleteCabinet(arg1:number):Promise<void>;

export function DeleteHardware(arg1:number):Promise<void>;

export function DeleteMaterial(arg1:number):Promise<void>;

export function DeleteQuote(arg1:number):Promise<void>;

export function DeleteQuoteBuyout(arg1:number):Promise<void>;

export function DeleteQuoteCabinet(arg1:number):Promise<void>;

export function DuplicateQuote(arg1:number):Promise<number>;

export function GetAssemblies(arg1:string):Promise<Array<models.Assembly>>;

export function GetCabinetCatalog():Promise<Array<models.Cabinet>>;

export function GetHardware():Promise<Array<models.Hardware>>;

export function GetMaterials():Promise<Array<models.Material>>;

export function GetQuoteDetail(arg1:number):Promise<models.QuoteDetailResponse>;

export function GetQuotes():Promise<Array<models.QuoteListItem>>;

export function GetShopSettings():Promise<models.ShopSettings>;

export function PrintQuote():Promise<void>;

export function SaveAssembly(arg1:models.Assembly):Promise<void>;

export function SaveCabinet(arg1:models.Cabinet):Promise<void>;

export function SaveHardware(arg1:models.Hardware):Promise<void>;

export function SaveMaterial(arg1:models.Material):Promise<void>;

export function SaveQuote(arg1:models.Quote):Promise<number>;

export function SaveShopSettings(arg1:models.ShopSettings):Promise<void>;

export function UpdateQuoteBuyout(arg1:models.QuoteBuyout):Promise<void>;

export function UpdateQuoteCabinet(arg1:models.QuoteCabinet):Promise<void>;
