// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddQuoteBuyout(arg1) {
  return window['go']['main']['App']['AddQuoteBuyout'](arg1);
}

export function AddQuoteCabinet(arg1) {
  return window['go']['main']['App']['AddQuoteCabinet'](arg1);
}

export function CalculateCabinetCost(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CalculateCabinetCost'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CalculateCabinetCostOverride(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['CalculateCabinetCostOverride'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function DeleteAssembly(arg1) {
  return window['go']['main']['App']['DeleteAssembly'](arg1);
}

export function DeleteCabinet(arg1) {
  return window['go']['main']['App']['DeleteCabinet'](arg1);
}

export function DeleteHardware(arg1) {
  return window['go']['main']['App']['DeleteHardware'](arg1);
}

export function DeleteMaterial(arg1) {
  return window['go']['main']['App']['DeleteMaterial'](arg1);
}

export function DeleteQuote(arg1) {
  return window['go']['main']['App']['DeleteQuote'](arg1);
}

export function DeleteQuoteBuyout(arg1) {
  return window['go']['main']['App']['DeleteQuoteBuyout'](arg1);
}

export function DeleteQuoteCabinet(arg1) {
  return window['go']['main']['App']['DeleteQuoteCabinet'](arg1);
}

export function DuplicateQuote(arg1) {
  return window['go']['main']['App']['DuplicateQuote'](arg1);
}

export function GetAssemblies(arg1) {
  return window['go']['main']['App']['GetAssemblies'](arg1);
}

export function GetCabinetCatalog() {
  return window['go']['main']['App']['GetCabinetCatalog']();
}

export function GetHardware() {
  return window['go']['main']['App']['GetHardware']();
}

export function GetMaterials() {
  return window['go']['main']['App']['GetMaterials']();
}

export function GetQuoteDetail(arg1) {
  return window['go']['main']['App']['GetQuoteDetail'](arg1);
}

export function GetQuotes() {
  return window['go']['main']['App']['GetQuotes']();
}

export function GetShopSettings() {
  return window['go']['main']['App']['GetShopSettings']();
}

export function PrintQuote() {
  return window['go']['main']['App']['PrintQuote']();
}

export function SaveAssembly(arg1) {
  return window['go']['main']['App']['SaveAssembly'](arg1);
}

export function SaveCabinet(arg1) {
  return window['go']['main']['App']['SaveCabinet'](arg1);
}

export function SaveHardware(arg1) {
  return window['go']['main']['App']['SaveHardware'](arg1);
}

export function SaveMaterial(arg1) {
  return window['go']['main']['App']['SaveMaterial'](arg1);
}

export function SaveQuote(arg1) {
  return window['go']['main']['App']['SaveQuote'](arg1);
}

export function SaveShopSettings(arg1) {
  return window['go']['main']['App']['SaveShopSettings'](arg1);
}

export function UpdateQuoteBuyout(arg1) {
  return window['go']['main']['App']['UpdateQuoteBuyout'](arg1);
}

export function UpdateQuoteCabinet(arg1) {
  return window['go']['main']['App']['UpdateQuoteCabinet'](arg1);
}
